// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdjhtqtxfcaxeltwxhjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkamh0cXR4ZmNheGVsdHd4aGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjEyMDUsImV4cCI6MjA2OTY5NzIwNX0.PCwTkShYSoGX1R4DE5AKLWZ90qJmlF4PBY26MbB9fiw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});